# Generated by Django 3.0.2 on 2020-01-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('agenda', models.TextField()),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('minutes', models.URLField()),
                ('resolutions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
