# Generated by Django 3.0.2 on 2020-01-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('BOARD', 'Board'), ('REGULAR', 'Regular')], default='REGULAR', max_length=20),
        ),
    ]
